const defaultTitle = "DEFAULT TITLE"

const unusedTitles = [
    "Vanguard Strike",
    "Iron Shield",
    "Crimson Wave",
    "Thunderous Resolve",
    "Eternal Vigilance",
    "Final Judgment",
    "Blaze of Glory",
    "Silent Thunder",
    "Stormfront Assault",
    "Rising Fury",
    "Echo of Liberty",
    "Steel Tempest",
    "Enduring Guardian",
    "Phoenix Dawn",
    "Titan’s Wrath",
    "Nightfall Protocol",
    "Vigilant Surge",
    "Storm Watch",
    "Braveheart Offensive",
    "Unyielding Horizon",
    "Falcon’s Fury",
    "Iron Requiem",
    "Black Tide",
    "Frostbite Strike",
    "Echo of Freedom",
    "Raging Inferno",
    "Zephyr Strike",
    "Iron Clad",
    "Silent Requiem",
    "Wraith’s Call",
    "Crimson Vortex",
    "Ruthless Edge",
    "Specter’s Reach",
    "Iron Resolve",
    "Shadow’s Wrath",
    "Phoenix Surge",
    "Midnight Tempest",
    "Vengeful Wrath",
    "Thunderstrike Protocol",
    "Ember Dawn",
    "Cold Fury",
    "Resonance Surge",
    "Wrath of the Fallen",
    "Havoc Protocol",
    "Aetheric Strike",
    "Ghostwave Offensive",
    "Rising Tides",
    "Crimson Dawn",
    "Silent Reign",
    "Wrath of Titan",
    "Iron Fury",
    "Shattered Echo",
    "Darkened Sky",
    "Brimstone Offensive",
    "Iron Ascendancy",
    "Titanic Resolve",
    "Shadowstorm Strike",
    "Steelwind Offensive",
    "Stormbreaker Protocol",
    "Red Dawn Assault",
    "Crimson Horizon",
    "Twilight Surge",
    "Unseen Fury",
    "Nightwatch Offensive",
    "Blaze of Freedom",
    "Iron Justice",
    "Braveheart Surge",
    "Endless Night",
    "Fury’s Edge",
    "Iron Wolf Strike",
    "Searing Light",
    "Steelheart Protocol",
    "Storm Forge",
    "Vigilance’s Call",
    "Silver Thunder",
    "Black Sky Offensive",
    "Eternal Nightfall",
    "Blazing Requiem",
    "Scorched Earth",
    "Silent Templar",
    "Iron Edge",
    "Wraith’s Reign",
    "Final Horizon",
    "Raging Storm",
    "Emberfall Protocol",
    "Shadowstrike Offensive",
    "Vengeful Night",
    "Blaze of the Phoenix",
    "Iron Resolve",
    "Frozen Fury",
    "Vigilant Storm",
    "Unbreakable Shield",
    "Phantom Surge",
    "Braveheart Reign",
    "Steelfire Strike",
    "Tempest Fury",
    "Crimson Edge",
    "Stormborn Offensive",
    "Dark Dawn",
    "Iron Flame",
    "Vengeful Fury",
    "Echo Storm",
    "Fury’s Dawn",
    "Rising Strike",
    "Searing Edge",
    "Shadowflare Offensive",
    "Iron Will",
    "Final Assault",
    "Resonant Flame",
    "Steel Requiem",
    "Ghoststrike Offensive",
    "Blazing Tides",
    "Phoenix Edge",
    "Wraith’s Fury",
    "Silent Vengeance",
    "Shadow Reborn",
    "Crimson Fury",
    "Stormshadow Offensive",
    "Iron Wrath",
    "Silent Requiem",
    "Stormborn Surge",
    "Blackfire Offensive",
    "Vengeful Storm",
    "Crimson Wrath",
    "Rising Tide",
    "Shattered Horizon",
];


const usedTitles = [];

export function getMissionTitle(): string {
    if (unusedTitles.length === 0) {
        return defaultTitle;    
    } else {
        const randomIndex = Math.floor(Math.random() * unusedTitles.length);
        const randomTitle = unusedTitles[randomIndex];
        unusedTitles.splice(randomIndex, 1);
        usedTitles.push(randomTitle);
        return randomTitle;
    }
}